### ISSUE TITLE
suggestion to make a wrapper around %chin%

### ISSUE THREAD

**Issue by iembry-USGS** [HughParsonage/hutils#1]
Hi, since you are importing from `data.table`, why don't you just make a wrapper around %chin% for both `notin` and `pin`?

Thank you.

Irucka Embry

**Comment by HughParsonage** [comment]
Thanks for the suggestion!

But I don't think `%chin%` is a full replacement in either case. From `?data.table::chmatch`:

> Methods that do build and cache a hash table (such as the fastmatch package) are *much* faster on subsequent calls (almost instant) but a little slower on the first. Therefore `chmatch` may be particularly suitable for ephemeral vectors (such as local variables in functions) or tasks that are only done once. Much depends on the length of `x` and `table`, how many unique strings each contains, and whether the position of the first match is all that is required.

In other words, `%chin%` is better than `%fin%` when called once, but not subsequently. Also `%chin%` is appropriate for character vectors but not other modes.

`%chin%` can't be used as a replacement for `%pin%` as they have different meanings: `x %pin% Y` is `TRUE` if for some `y` in `Y`, `grepl(y, x, perl = TRUE)` is `TRUE`. For example:

```r
x <- c("Sydney Airport", "Melbourne Airport")
x %pin% c("Syd", "Melb")
#> [1] TRUE TRUE

x %in% c("Syd", "Melb")
x %fin% c("Syd", "Melb")
x %chin% c("Syd", "Melb")
#> [1] FALSE FALSE
```

Let me know if this isn't (or wasn't) clear, as that's a failure of the documentation.

**Comment by iembry-USGS** [comment]
@HughParsonage  Thank you for the wonderful explanation and examples. You have definitely persuaded me to withdraw my suggestion.

Irucka
